server:
  port: 80 #端口
spring:
  thymeleaf:
    mode: LEGACYHTML5 #非标准加载html5需配合nekohtml使用
    cache: false
    content-type: text/html; charset=utf-8
    encoding: UTF-8
shiro:
  loginUrl: /login.html
  successUrl: /index
  unauthorizedUrl: /unauthorized
  sessionManager:
    sessionIdUrlRewritingEnabled: false