spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/sso?autoReconnect=true&characterEncoding=utf8&useSSL=true
    username: root
    password: nlj123
  redis:
    database: 3
    host: 127.0.0.1
    password: 
    port: 6379
    timeout: 3000 #连接超时时间 单位 ms（毫秒）
    pool:
      max-idle: 500 #连接池中的最大空闲连接
      min-idle: 50
      max-wait: 1000 #等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException

#################redis哨兵设置#################
# Redis服务器master的名字
#spring.redis.sentinel.master=mastername
# redis-sentinel的配置地址和端口
#spring.redis.sentinel.nodes=127.0.0.1:6379,192.168.1.1:6380,192.168.1.2:6380
  
#mybatis分页
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

